apiVersion : apps/v1
kind: Deployment
metadata:
  name: publicnodejs 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publicnodejs
  template:
    metadata:
      labels:
        app: publicnodejs 
    spec:
      containers:
        - name: publicnodejs 
          image: kcscr.azurecr.io/publicnodejs
          ports:
          - containerPort: 3000
